# Generated by Django 2.1.7 on 2019-03-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(default='NULL', max_length=100)),
                ('activity_level', models.CharField(default='NULL', max_length=7)),
                ('coat_length', models.CharField(default='NULL', max_length=7)),
                ('drools', models.BooleanField(default='NULL', max_length=7)),
                ('good_with_children', models.BooleanField(default='NULL', max_length=7)),
                ('grooming_demand', models.CharField(default='NULL', max_length=7)),
                ('intelligence', models.CharField(default='NULL', max_length=7)),
                ('shedding_level', models.CharField(default='NULL', max_length=7)),
                ('size', models.CharField(default='NULL', max_length=12)),
                ('imageName', models.CharField(default='NULL', max_length=100)),
            ],
        ),
    ]
